CREATE TABLE `memmaster` (
  `Member_Code` varchar(13) NOT NULL DEFAULT '',
  `Member_TypeCode` char(2) NOT NULL DEFAULT '00',
  `Member_BranchCode` char(3) NOT NULL DEFAULT '000',
  `Member_Gender` char(1) NOT NULL DEFAULT 'M',
  `Member_Status` char(2) NOT NULL DEFAULT 'S',
  `Member_NationCode` char(2) NOT NULL DEFAULT '00',
  `Member_OccupationCode` char(1) NOT NULL DEFAULT '0',
  `Member_IncomeCode` char(1) NOT NULL DEFAULT '0',
  `Member_EducationCode` char(3) NOT NULL DEFAULT '000',
  `Member_HomeTel` varchar(30) DEFAULT NULL,
  `Member_Email` varchar(50) DEFAULT NULL,
  `Member_Brithday` date NOT NULL,
  `Member_ExpiredDate` date NOT NULL,
  `Member_TotalPurchase` float(10,2) NOT NULL DEFAULT '0.00',
  `Member_Mobile` varchar(30) DEFAULT NULL,
  `Member_PointExpiredDate` date NOT NULL,
  `Member_TotalScore` float(14,0) NOT NULL DEFAULT '0',
  `Member_TitleNameThai` varchar(20) DEFAULT ' ',
  `Member_Active` char(1) NOT NULL DEFAULT 'Y',
  `Username` varchar(100) NOT NULL,
  `Password` varchar(100) NOT NULL,
  `Member_FirstName` varchar(100) DEFAULT NULL,
  `Member_LastName` varchar(100) DEFAULT NULL,
  `System_Created` datetime DEFAULT NULL,
  `System_Updated` datetime DEFAULT NULL,
  PRIMARY KEY (`Member_Code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
