CREATE TABLE IF NOT EXISTS `memmaster` (
  `Member_Code` varchar(13) NOT NULL DEFAULT '',
  `Member_TypeCode` char(2) NOT NULL DEFAULT '00',
  `Member_BranchCode` char(3) NOT NULL DEFAULT '000',
  `Member_NameThai` varchar(50) DEFAULT ' ',
  `Member_NameEng` varchar(50) DEFAULT ' ',
  `Member_Gender` char(1) NOT NULL DEFAULT 'M',
  `Member_Status` char(2) NOT NULL DEFAULT 'S',
  `Member_NationCode` char(2) NOT NULL DEFAULT '00',
  `Member_OccupationCode` char(1) NOT NULL DEFAULT '0',
  `Member_IncomeCode` char(1) NOT NULL DEFAULT '0',
  `Member_EducationCode` char(3) NOT NULL DEFAULT '000',
  `Member_Company` varchar(50) DEFAULT NULL,
  `Member_AddressNo` varchar(15) DEFAULT NULL,
  `Member_Building` varchar(250) DEFAULT ' ',
  `Member_AddressSoi` varchar(30) DEFAULT NULL,
  `Member_AddressStreet` varchar(30) DEFAULT NULL,
  `Member_AddressSubDistrict` varchar(30) DEFAULT NULL,
  `Member_AddressDistrict` varchar(30) DEFAULT NULL,
  `Member_Province` varchar(30) DEFAULT NULL,
  `Member_PostalCode` varchar(5) DEFAULT NULL,
  `Member_HomeTel` varchar(30) DEFAULT NULL,
  `Member_Fax` varchar(15) DEFAULT NULL,
  `Member_Email` varchar(50) DEFAULT NULL,
  `Member_Brithday` date NOT NULL,
  `Member_AppliedDate` date NOT NULL,
  `Member_ExpiredDate` date NOT NULL,
  `Member_DiscountRate` varchar(8) DEFAULT '00/00/00',
  `Member_SpouseName` varchar(50) DEFAULT NULL,
  `Member_Food` varchar(50) DEFAULT NULL,
  `Member_TotalPurchase` float(10,2) NOT NULL DEFAULT '0.00',
  `Member_Remark1` varchar(50) DEFAULT NULL,
  `Member_Remark2` varchar(50) DEFAULT NULL,
  `Member_Mobile` varchar(30) DEFAULT NULL,
  `Member_ReceiveInformation` char(1) NOT NULL DEFAULT 'M',
  `Member_HobbySetCode` varchar(100) DEFAULT NULL,
  `Member_LastDateService` date NOT NULL,
  `Member_ServiceCount` float(14,0) NOT NULL DEFAULT '0',
  `Member_PointExpiredDate` date NOT NULL,
  `Member_TotalScore` float(14,0) NOT NULL DEFAULT '0',
  `Member_TitleNameThai` varchar(20) DEFAULT ' ',
  `Member_SurnameThai` varchar(50) DEFAULT ' ',
  `Member_CompanyAddressNo` varchar(15) DEFAULT NULL,
  `Member_CompanyBuilding` varchar(30) DEFAULT NULL,
  `Member_CompanySoi` varchar(30) DEFAULT NULL,
  `Member_CompanyStreet` varchar(30) DEFAULT NULL,
  `Member_CompanySubDistrict` varchar(30) DEFAULT NULL,
  `Member_CompanyDistrict` varchar(30) DEFAULT NULL,
  `Member_CompanyProvince` varchar(30) DEFAULT NULL,
  `Member_CompanyPostalCode` varchar(5) DEFAULT NULL,
  `Member_CompanyTel` varchar(30) DEFAULT NULL,
  `Member_CompanyFax` varchar(15) DEFAULT NULL,
  `Member_Active` char(1) NOT NULL DEFAULT 'Y',
  `Member_UsedTitle` char(1) NOT NULL DEFAULT 'Y',
  `Member_MailTo` char(1) DEFAULT '0',
  `Member_PrintLabel` char(1) NOT NULL DEFAULT 'N',
  `Employee_CodeCreate` varchar(20) NOT NULL DEFAULT '000000',
  `Employee_CreateDate` date NOT NULL,
  `Employee_CreateTime` time NOT NULL DEFAULT '00:00:00',
  `Employee_CodeModify` varchar(20) NOT NULL DEFAULT '000000',
  `Employee_ModifyDate` date NOT NULL,
  `Employee_ModifyTime` time NOT NULL DEFAULT '00:00:00',
  `Member_TranferFlag` char(1) NOT NULL DEFAULT 'N',
  `Member_UnknowBirth` char(1) NOT NULL DEFAULT 'N',
  `Member_PriceNO` varchar(1) NOT NULL DEFAULT '1',
  `System_Created` datetime DEFAULT NULL,
  `System_Updated` datetime DEFAULT NULL,
  PRIMARY KEY (`Member_Code`)
);

CREATE TABLE IF NOT EXISTS `redeem` (
  `uuid_index` varchar(36) NOT NULL,
  `redeem_code` varchar(30) DEFAULT NULL COMMENT 'รหัส qr code',
  `product_code` varchar(20) DEFAULT NULL COMMENT 'รหัสสินค้า',
  `point_to_redeem` int(10) DEFAULT NULL COMMENT 'แต้มที่ลด',
  `use_in_branch` varchar(30) DEFAULT NULL COMMENT 'สาขาที่ไปใช้',
  `emp_code_redeem` varchar(30) DEFAULT NULL COMMENT 'รหัสพนักงาน',
  `member_code_use` varchar(30) DEFAULT NULL COMMENT 'รหัสสมาชิก',
  `qty_in_use` int(3) DEFAULT NULL COMMENT 'จำนวนที่ใช้',
  `system_create` datetime DEFAULT NULL COMMENT 'วันที่สร้าง',
  `redeem_date` datetime DEFAULT NULL COMMENT 'วันที่นำไปใช้',
  `in_time` datetime DEFAULT NULL COMMENT 'ใช้ภายในระยะเวลา',
  `status_use` varchar(20) DEFAULT NULL COMMENT 'คำอธิบาย สถานะ',
  `active` varchar(1) DEFAULT NULL COMMENT 'flag  active',
  `redeem_name` varchar(250) DEFAULT NULL COMMENT 'ชื่อการใช้งาน',
  `bill_no` varchar(100) DEFAULT NULL COMMENT 'เลขที่เอกสาร',
  `discount_amt` float(10,2) DEFAULT NULL COMMENT 'จำนวนเงินที่ลด',
  `discount_percent` float(5,2) DEFAULT NULL COMMENT 'จำนวนเงินที่ลด เปอร์เซ็นต์',
  `redeem_or_free` char(1) DEFAULT NULL COMMENT 'ประเภท ลด(R) หรือแถม(F)',
  `data_sync` char(1) DEFAULT 'N' COMMENT 'ดึงข้อมูลไป local'
);
